name: 'Set Issue Label'
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: naturalclar/issue-action@v0.0.1
        with:
          keywords: 'feature'
          action: 'label Feature'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
