name: 'Set Issue Label'
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["post"]'
          action: '["Post Idea"]'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["feature"]'
          action: '["feature request"]'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
